version: '3.3'
services:
    web:
        container_name: web
        build: ./apka
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        depends_on:
            - redis
    
    redis:
        container_name: redis
        image: "redis:alpine"
        command: redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes
        ports:
            - 6379:6379
        volumes:
            - dataRedis:/data


    haproxy:
       container_name: haproxy
       build: ./haproxy
       volumes:
            - ./ssl2/:/etc/ssl/certs/
       ports:
            - "443:443"
       depends_on:
            - web

volumes:
       dataRedis:
